### ISSUE TITLE
 Fix memory issue on the KU Django server

### ISSUE THREAD

**Issue by acwhite211** [specify/specify.github.io#3]
After some investigation, it seems after adding new Specify instances to the KU server, it has become pretty tight on memory and storage. We'll need to increase the swap memory for now, but we should look into adding more memory or storage to the server in the future.

```
                   total        used        free      
Mem:          5.5Gi       3.9Gi       118Mi       
Swap:         4.0Gi       3.9Gi        28Mi
```

**Comment by beach53** [comment]
That seems like a small amount of memory, is that a VM that KU IT can then
ramp up the ram on?

Just curious how many Specify instances do we run on the KU server?


James H. Beach, Executive Director
Specify Collections Consortium
Biodiversity Institute
University of Kansas
1345 Jayhawk Boulevard
Lawrence, KS 66045, USA

***@***.***
www.specifysoftware.org
Office: +1 785.864.4645
Cell: +1 785.331.8508
